WITH s as (
SELECT 
  convert(datetime,SWITCHOFFSET(CONVERT(DATETIMEOFFSET(3), COALESCE(lastactivetime, disc.lastdiscoverytime)), DATENAME(TzOffset, SYSDATETIMEOFFSET()))) as [timestamp],
  machineid as resourceid, 
  CASE architecturekey
    WHEN 5 THEN 'system'
	WHEN 2 THEN 'unknown system'
  END as resource_type, 
  name, 
  smsid, 
  sitecode, 
  domain, 
  clientedition, 
  clienttype, 
  clientversion, 
  isclient, 
  isobsolete, 
  isactive, 
  isvirtualmachine, 
  isaoaccapable, 
  deviceowner, 
  suppressautoprovision, 
  isapproved, 
  isblocked, 
  isalwaysinternet, 
  isinternetenabled, 
  clientcerttype, 
  username, 
  lastclientchecktime, 
  clientcheckpass, 
  adsitename, 
  userdomainname, 
  adlastlogontime as adlastlogontime_epoch, 
  clientremediationsuccess, 
  clientactivestatus, 
  convert(datetime,SWITCHOFFSET(CONVERT(DATETIMEOFFSET(3), laststatusmessage), DATENAME(TzOffset, SYSDATETIMEOFFSET()))) as laststatusmessage_epoch,
  convert(datetime,SWITCHOFFSET(CONVERT(DATETIMEOFFSET(3), lastpolicyrequest), DATENAME(TzOffset, SYSDATETIMEOFFSET()))) as lastpolicyrequest_epoch,
  lastddr as lastddr_epoch, 
  convert(datetime,SWITCHOFFSET(CONVERT(DATETIMEOFFSET(3), lasthardwarescan), DATENAME(TzOffset, SYSDATETIMEOFFSET()))) as lasthardwarescan_epoch,
  convert(datetime,SWITCHOFFSET(CONVERT(DATETIMEOFFSET(3), lastsoftwarescan), DATENAME(TzOffset, SYSDATETIMEOFFSET()))) as lastsoftwarescan_epoch,
  lastmpservername, 
  convert(datetime,SWITCHOFFSET(CONVERT(DATETIMEOFFSET(3), COALESCE(lastactivetime, disc.lastdiscoverytime)), DATENAME(TzOffset, SYSDATETIMEOFFSET()))) as lastactivetime_epoch,
  cp_status, 
  cp_latestprocessingattempt, 
  cp_lastinstallationerror, 
  deviceos, 
  ep_deploymentstate, 
  ep_deploymenterrorcode, 
  ep_deploymentdescription, 
  ep_policyapplicationstate, 
  ep_policyapplicationerrorcode, 
  ep_policyapplicationdescription, 
  ep_enabled, 
  ep_clientversion, 
  ep_productstatus, 
  ep_engineversion, 
  ep_antivirusenabled, 
  ep_antivirussignatureversion, 
  convert(datetime,SWITCHOFFSET(CONVERT(DATETIMEOFFSET(3), ep_antivirussignatureupdatedatetime), DATENAME(TzOffset, SYSDATETIMEOFFSET()))) as ep_antivirussignatureupdatedatetime_epoch,
  ep_antispywareenabled, 
  ep_antispywaresignatureversion, 
  convert(datetime,SWITCHOFFSET(CONVERT(DATETIMEOFFSET(3), ep_antispywaresignatureupdatedatetime), DATENAME(TzOffset, SYSDATETIMEOFFSET()))) as ep_antispywaresignatureupdatedatetime_epoch,
  convert(datetime,SWITCHOFFSET(CONVERT(DATETIMEOFFSET(3), ep_lastfullscandatetimestart), DATENAME(TzOffset, SYSDATETIMEOFFSET()))) as ep_lastfullscandatetimestart_epoch,
  convert(datetime,SWITCHOFFSET(CONVERT(DATETIMEOFFSET(3), ep_lastfullscandatetimeend), DATENAME(TzOffset, SYSDATETIMEOFFSET()))) as ep_lastfullscandatetimeend_epoch,
  convert(datetime,SWITCHOFFSET(CONVERT(DATETIMEOFFSET(3), ep_lastquickscandatetimestart), DATENAME(TzOffset, SYSDATETIMEOFFSET()))) as ep_lastquickscandatetimestart_epoch,
  convert(datetime,SWITCHOFFSET(CONVERT(DATETIMEOFFSET(3), ep_lastquickscandatetimeend), DATENAME(TzOffset, SYSDATETIMEOFFSET()))) as ep_lastquickscandatetimeend_epoch,
  ep_infectionstatus, 
  ep_pendingfullscan, 
  ep_pendingreboot, 
  ep_pendingmanualsteps, 
  ep_pendingofflinescan, 
  convert(datetime,SWITCHOFFSET(CONVERT(DATETIMEOFFSET(3), ep_lastinfectiontime), DATENAME(TzOffset, SYSDATETIMEOFFSET()))) as ep_lastinfectiontime_epoch,
  ep_lastthreatname, 
  unknown 
FROM v_combineddeviceresources
INNER JOIN (
  select 
  ResourceId, 
  max(agenttime) as lastdiscoverytime
from v_agentdiscoveries group by ResourceId
) as disc
  on disc.ResourceId = v_combineddeviceresources.machineid)
select * from s
{{WHERE $rising_column$ > ?}}